/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package myjava.projects;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

// import myjava.myprojects.App;

class AppTest {
    @Test
    void appHasAGreeting() {
        // App classUnderTest = new App();
        assertNotNull("app should have a greeting");
    }
}
